# Generated by Django 5.0.1 on 2025-11-10 09:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=500)),
                ('primary_image', models.ImageField(help_text='Main product image (high resolution recommended)', upload_to='products/')),
                ('uom', models.CharField(choices=[('kg', 'Kilogram'), ('lbs', 'Pounds'), ('pieces', 'Pieces'), ('carton', 'Carton'), ('box', 'Box')], default='kg', max_length=20, verbose_name='Unit of Measure')),
                ('weight_volume', models.DecimalField(decimal_places=2, help_text='Weight or volume per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('moq', models.IntegerField(help_text='Minimum quantity required for order', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Order Quantity')),
                ('storage_temp_min', models.DecimalField(decimal_places=2, default=-40.0, help_text='Minimum storage temperature in Celsius', max_digits=5, verbose_name='Min Storage Temperature (°C)')),
                ('storage_temp_max', models.DecimalField(decimal_places=2, default=-18.0, help_text='Maximum storage temperature in Celsius', max_digits=5, verbose_name='Max Storage Temperature (°C)')),
                ('packaging_type', models.CharField(help_text='e.g., Vacuum-sealed, IQF, Bulk', max_length=100)),
                ('units_per_carton', models.IntegerField(help_text='Number of units per carton', validators=[django.core.validators.MinValueValidator(1)])),
                ('carton_dimensions', models.CharField(blank=True, help_text='e.g., 40cm x 30cm x 20cm', max_length=100)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Gross weight per carton (kg)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('certifications', models.TextField(blank=True, help_text='e.g., HACCP, ISO, Halal, Organic')),
                ('shelf_life', models.CharField(blank=True, help_text='e.g., 24 months from production', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-is_featured', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'),
        ),
    ]
