# Generated by Django 5.0.1 on 2025-11-10 09:14

import django.core.validators
import django.db.models.deletion
import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(default=quotes.models.generate_quote_number, editable=False, max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, help_text='Additional message or requirements from customer')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('quoted', 'Quote Sent'), ('converted', 'Converted to Order'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for sales team (not visible to customer)')),
                ('total_items', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='quotes_quot_submitt_de5aed_idx'), models.Index(fields=['status', '-submitted_at'], name='quotes_quot_status_748943_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Requested quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Specific notes for this product')),
                ('product_name', models.CharField(max_length=255)),
                ('product_uom', models.CharField(max_length=20)),
                ('product_moq', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
